### ISSUE TITLE
Confirm that hard XAS data from NSLS-II has been ingested

### ISSUE THREAD

**Issue by danielballan** [AI-multimodal/aimmdb#31]
This is item 5c in the Google doc. Data owner is Eli.

Data comprises Co, Ni, Mn K-edge of NMC. This may already be ingested as `iss` / `iss-raw` (processed and unprocessed, respectively). It should be moved under the `ncm` dataset, though it should retain some indication of the batch that it came from under some other metadata.

**Comment by jmaruland** [comment]
I met with Eli and he showed me the files that he has in his shared folder. I could identify the files that are in `aimmdb` already (18 samples in the `iss` dataset). He pointed out to a subfolder called `new` where there are additional files that should be and he thought they were in `aimmdb` already.
We didn't move them to `aimmdb` because Eli was not sure if the NMC data in his shared folder was complete. We will talk again before the end of the week and continue where we left off.

**Comment by jmaruland** [comment]
The files in the second batch of data from NSLS-II that I received did not contain the correct information about the experiment. This was notified and a document that include some table with the experiment configuration was provided. The document had to go for a second revision because some of the information was not correct. Once these issues were solved, all the data in this second batch was uploaded to aimmdb.
At this moment, all the data from NSLS-II has been uploaded to aimmdb

**Comment by jmaruland** [comment]
How to find all the APS data in aimmdb:
```
In [38]: c['dataset']['nmc']['uid'].search(Key("facility.name") == "NSLS-II")
Out[38]: <AIMMCatalog {BM_NCM622 Mn-K (cQgsgjQC9ja), ...} ~133 entries>
```
where `c` is the tiled-client object
